# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/felix/Code/cell_automata_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/felix/Code/cell_automata_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.30.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/felix/Code/cell_automata_project/CMakeFiles /Users/felix/Code/cell_automata_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/felix/Code/cell_automata_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CellularAutomata3D

# Build rule for target.
CellularAutomata3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CellularAutomata3D
.PHONY : CellularAutomata3D

# fast build rule for target.
CellularAutomata3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/build
.PHONY : CellularAutomata3D/fast

generated/sim_server.grpc.pb.o: generated/sim_server.grpc.pb.cc.o
.PHONY : generated/sim_server.grpc.pb.o

# target to build an object file
generated/sim_server.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.grpc.pb.cc.o
.PHONY : generated/sim_server.grpc.pb.cc.o

generated/sim_server.grpc.pb.i: generated/sim_server.grpc.pb.cc.i
.PHONY : generated/sim_server.grpc.pb.i

# target to preprocess a source file
generated/sim_server.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.grpc.pb.cc.i
.PHONY : generated/sim_server.grpc.pb.cc.i

generated/sim_server.grpc.pb.s: generated/sim_server.grpc.pb.cc.s
.PHONY : generated/sim_server.grpc.pb.s

# target to generate assembly for a file
generated/sim_server.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.grpc.pb.cc.s
.PHONY : generated/sim_server.grpc.pb.cc.s

generated/sim_server.pb.o: generated/sim_server.pb.cc.o
.PHONY : generated/sim_server.pb.o

# target to build an object file
generated/sim_server.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.pb.cc.o
.PHONY : generated/sim_server.pb.cc.o

generated/sim_server.pb.i: generated/sim_server.pb.cc.i
.PHONY : generated/sim_server.pb.i

# target to preprocess a source file
generated/sim_server.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.pb.cc.i
.PHONY : generated/sim_server.pb.cc.i

generated/sim_server.pb.s: generated/sim_server.pb.cc.s
.PHONY : generated/sim_server.pb.s

# target to generate assembly for a file
generated/sim_server.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/generated/sim_server.pb.cc.s
.PHONY : generated/sim_server.pb.cc.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/random_bitset.o: src/random_bitset.cpp.o
.PHONY : src/random_bitset.o

# target to build an object file
src/random_bitset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/random_bitset.cpp.o
.PHONY : src/random_bitset.cpp.o

src/random_bitset.i: src/random_bitset.cpp.i
.PHONY : src/random_bitset.i

# target to preprocess a source file
src/random_bitset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/random_bitset.cpp.i
.PHONY : src/random_bitset.cpp.i

src/random_bitset.s: src/random_bitset.cpp.s
.PHONY : src/random_bitset.s

# target to generate assembly for a file
src/random_bitset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/random_bitset.cpp.s
.PHONY : src/random_bitset.cpp.s

src/world_state.o: src/world_state.cpp.o
.PHONY : src/world_state.o

# target to build an object file
src/world_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/world_state.cpp.o
.PHONY : src/world_state.cpp.o

src/world_state.i: src/world_state.cpp.i
.PHONY : src/world_state.i

# target to preprocess a source file
src/world_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/world_state.cpp.i
.PHONY : src/world_state.cpp.i

src/world_state.s: src/world_state.cpp.s
.PHONY : src/world_state.s

# target to generate assembly for a file
src/world_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CellularAutomata3D.dir/build.make CMakeFiles/CellularAutomata3D.dir/src/world_state.cpp.s
.PHONY : src/world_state.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CellularAutomata3D"
	@echo "... generated/sim_server.grpc.pb.o"
	@echo "... generated/sim_server.grpc.pb.i"
	@echo "... generated/sim_server.grpc.pb.s"
	@echo "... generated/sim_server.pb.o"
	@echo "... generated/sim_server.pb.i"
	@echo "... generated/sim_server.pb.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/random_bitset.o"
	@echo "... src/random_bitset.i"
	@echo "... src/random_bitset.s"
	@echo "... src/world_state.o"
	@echo "... src/world_state.i"
	@echo "... src/world_state.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

